application: jaddy-blog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /resources
  static_dir: static_folder

- url: .*
  script: main.app
  handlers:

- url: /profile/.*
  script: _go_app
  login: required

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
